"""
p11_control_period_sweep.py  --  P2.8b: at what control rate does the target break?
REVISION 5 -- block count is now PER SEQUENCE, because convergence is.

PLACE THIS FILE AT:   C:\\Users\\user\\gmppt\\phase2\\p11_control_period_sweep.py
                      OVERWRITE revision 4. gmppt/dynamic.py is NOT modified.

RUN FROM THE REPO ROOT (C:\\Users\\user\\gmppt):
    python phase2\\p11_control_period_sweep.py --sequence 30-100
    python phase2\\p11_control_period_sweep.py --sequence 10-50

WHY THIS RUN EXISTS

    P2.8 met the funded dynamic target at 99.911% -- and found that the profile
    does not discriminate. Every method whose cost is independent of block length
    was flat across a tenfold slope range: the hybrid moved 0.005 pt, and P&O
    moved 0.088 pt in the WRONG direction.

    The reason is measured. At a 100 ms control period the fastest ramp in
    Sequence B still occupies 364 control steps while the peak moves only 0.79 V
    (1.9% of V_oc). P&O's perturbation step is roughly 0.22 V. Following a target
    that slow costs nothing, so no slope in the sequence is difficult.

    100 ms was DECLARED, not measured -- the partner's control period is
    outstanding. It is therefore the one parameter that can be swept to find
    where the problem becomes hard.

WHAT REVISION 5 CHANGES, AND THE FINDING BEHIND IT

    Revision 4 ran Sequence 30-100 successfully: check 0 measured 0.001 pt
    between 6 and 12 blocks per phase, well inside the declared 0.1 pt, so the
    block discretisation was converged and P2.8's headline figure carries no
    discretisation error.

    Run on Sequence 10-50 with the same block count, CHECK 0 FAILED: 0.330 pt
    between 6 and 12 blocks, more than three times the tolerance. The run stopped
    before producing any figure.

    THE FINDING: BLOCK CONVERGENCE IS SEQUENCE-DEPENDENT.

    Sequence 30-100 spans 300 to 1000 W/m2. Sequence 10-50 spans 100 to 500, and
    Sequence 1-10 spans 11 to 100. At low irradiance a panel's power curve is
    steeply nonlinear: the peak voltage shifts more per unit of irradiance change
    and the curve shape distorts. Six blocks approximate that badly. Higher up,
    where the curves are closer to linear in irradiance, six suffice.

    So a block count validated on one sequence CANNOT be carried to another, and
    P2.8's 99.911% is validated for Sequence 30-100 ONLY.

    Revision 5 makes the block count a PER-SEQUENCE declared value and forces
    check 0 to run at whatever value the chosen sequence declares. That removes
    the possibility of inheriting a count someone validated elsewhere -- which is
    what revision 4 did by accident.

THE HISTORY OF THIS FILE, RECORDED RATHER THAN TIDIED AWAY

    REVISION 1 -- defect D19. MIN_STEPS_PER_TRAJECTORY was carried, a note was
    printed when a configuration violated it, and the configuration was included
    in the verdict anyway. Past a certain period every block hits make_profile's
    one-step floor, the profile stops shrinking, and different slopes produce
    IDENTICAL trajectories -- 8000 ms and 16000 ms both gave 36 steps and
    byte-identical results, so criterion 3 FAILED on rows where the slope
    distinction had degenerated by construction. Over the well-formed range the
    gap widened cleanly: +0.006, +0.159, +0.611, +1.120.

    REVISION 2 excluded degenerate configurations automatically but tested for
    them with MIN_STEPS_PER_TRAJECTORY = 60 -- a proxy, and a poor one. It
    excluded 1000 ms (52 steps), which was not degenerate.

    REVISION 3 restated the rule correctly on steps PER BLOCK -- that stands --
    and raised blocks_per_phase 6 -> 24 on the reasoning that finer resolution
    would keep blocks well-formed. THAT REASONING WAS BACKWARDS: steps_for()
    divides a phase's steps AMONG its blocks, so more blocks means fewer steps
    each and degeneracy arrives EARLIER. Six of seven configurations failed.

    REVISION 4 reverted to 6, justified by revision 3's own check 0 (0.002 pt
    between 12 and 24). Sequence 30-100 then ran correctly. Sequence 10-50
    failed check 0, producing the finding above.

A WALL SEQUENCE 30-100 CANNOT PASS -- recorded as a bound, not worked around

    Its fastest ramp lasts 7 seconds. At a 1000 ms control period, with 6 blocks
    per ramp, each block holds a single step and the floor binds. Lowering the
    block count buys one configuration per halving, and at one block per ramp the
    ramp is no longer a ramp but a step change.

    Before the TRACKER degrades enough to fail the target, the PROFILE stops
    being a ramp. The fast-slope break point cannot be located with that
    sequence at any block setting.

    Sequence 10-50 has ramps up to 800 s uncompressed and is where a break point
    can plausibly be found -- which is why its block count had to be established
    first.

    This is the SECOND independent reason -- alongside the peak moving only ~2%
    of V_oc -- that shading-PATTERN transitions rather than irradiance ramps are
    the experiment for dynamic response. EN 50530 cannot produce a peak
    relocation: it assumes a single peak.

DECLARED BEFORE THE RUN

    (0) BLOCK CONVERGENCE, AT THE SEQUENCE'S OWN DECLARED COUNT. Doubling the
        block count must move efficiency by less than dynamic.py's
        BLOCK_CONVERGENCE_PT. If it does not, every figure from that sequence
        carries a discretisation error larger than the differences being
        reported, and nothing may be read.

    (1) The BREAK POINT is the largest control period at which the hybrid still
        aggregates >= 99% on shaded scenarios.

    (2) Efficiency must be MONOTONE in the control period.

    (3) Fast slopes must break BEFORE slow ones.

    (1) through (3) are evaluated over VALID configurations only.

THE VALIDITY RULE (D19, as corrected in revision 3)

    A configuration decides a criterion only if every block holds at least
    MIN_STEPS_PER_BLOCK control steps, AND its step counts differ from the
    previous period. Excluded configurations are still RUN and REPORTED -- they
    show exactly where the profile stops working.

METHOD COVERAGE
    The hybrid, P&O and seed-only, plus the oracle. PSO and the re-seeding
    variant are excluded deliberately: their costs scale with the step count, so
    slowing the controller changes their PROBE BUDGET as well as their tracking
    difficulty. That confound is defect D18.

SCOPE
    Training-module scenarios, shaded only. All figures simulated.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gmppt import config  # noqa: E402
from gmppt.dynamic import (BLOCK_CONVERGENCE_PT, SEQUENCES,  # noqa: E402
                           DynamicTrajectory, aggregate_efficiency,
                           dynamic_trajectory_for, make_profile)
from gmppt.harness import scenario_set  # noqa: E402
from gmppt.hybrid import SEED_PROBE_COST, seed_voltage  # noqa: E402
from gmppt.model import TwoStageModel  # noqa: E402
from gmppt.tracking import DEFAULT_STEP_FRAC, START_FRACTION  # noqa: E402

OUT = config.RESULTS_DIR / "phase2"

PERIOD_SWEEP = (0.1, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0)

TARGET_PCT = 99.0

# Degeneracy is a block holding a single control step, at which point the profile
# stops shrinking as the period grows. Directly checkable rather than proxied by
# trajectory length.
MIN_STEPS_PER_BLOCK = 2

# ---------------------------------------------------------------------------
# BLOCK COUNT PER SEQUENCE -- because convergence is sequence-dependent.
#
# 30-100  spans 300-1000 W/m2. Measured converged at 6: 0.001 pt against 12, and
#         0.002 pt between 12 and 24 in revision 3. Curves are close to linear in
#         irradiance up there, so coarse blocks approximate them well.
#
# 10-50   spans 100-500 W/m2. FAILED at 6: 0.330 pt against 12, more than three
#         times the tolerance. Low-irradiance curves are steeply nonlinear -- the
#         peak voltage shifts more per unit irradiance and the shape distorts --
#         so finer blocks are required. Declared at 24; check 0 must pass at
#         24 vs 48 before anything from this sequence is read.
#
# 1-10    spans 11-100 W/m2, an order of magnitude dimmer still. Declared at 24
#         as a starting point on the same reasoning, and UNTESTED. Check 0
#         decides it.
#
# A count validated on one sequence must never be carried to another. Revision 4
# did that by accident and check 0 caught it.
# ---------------------------------------------------------------------------
BLOCKS_PER_PHASE = {
    "30-100": 6,
    "10-50": 24,
    "1-10": 24,
}


# ---------------------------------------------------------------------------
# TRACKERS
# ---------------------------------------------------------------------------

def t_oracle(traj: DynamicTrajectory, model=None, **_) -> None:
    for _ in range(traj.n_steps):
        traj.step(traj.curves[traj.block_index][2])


def t_po(traj: DynamicTrajectory, model=None,
         step_frac: float = DEFAULT_STEP_FRAC, **_) -> None:
    dv = step_frac * traj.v_oc
    v = START_FRACTION * traj.v_oc
    p_prev = traj.step(v)
    direction = -1.0
    for _ in range(traj.n_steps - 1):
        v = v + direction * dv
        p = traj.step(v)
        if p < p_prev:
            direction = -direction
        p_prev = p


def t_seed_only(traj: DynamicTrajectory, model: TwoStageModel,
                temp_c: float = 25.0, **_) -> None:
    v_seed, _ = seed_voltage(traj, model, temp_c)
    for _ in range(traj.n_steps - SEED_PROBE_COST):
        traj.step(v_seed)


def t_hybrid(traj: DynamicTrajectory, model: TwoStageModel,
             temp_c: float = 25.0, step_frac: float = DEFAULT_STEP_FRAC,
             **_) -> None:
    v_seed, _ = seed_voltage(traj, model, temp_c)
    n = traj.n_steps - SEED_PROBE_COST
    if n <= 0:
        return
    dv = step_frac * traj.v_oc
    v = float(min(max(v_seed, traj.v_floor), traj.v_oc))
    p_prev = traj.step(v)
    direction = -1.0
    for _ in range(n - 1):
        v = float(min(max(v + direction * dv, traj.v_floor), traj.v_oc))
        p = traj.step(v)
        if p < p_prev:
            direction = -direction
        p_prev = p


METHODS = [
    ("oracle [not buildable]", t_oracle),
    ("P&O", t_po),
    ("seed only", t_seed_only),
    ("hybrid", t_hybrid),
]


# ---------------------------------------------------------------------------
# RUNNER
# ---------------------------------------------------------------------------

def run_at_period(scenarios, sequence: str, period_s: float,
                  model: TwoStageModel, cycles: int,
                  blocks_per_phase: int) -> dict:
    """Every method at one control period. Curves cached per scenario+slope."""
    _, rows = SEQUENCES[sequence]
    profiles = [make_profile(sequence, r[1],
                             blocks_per_phase=blocks_per_phase,
                             control_period_s=period_s,
                             max_cycles=cycles) for r in rows]

    cache = {}
    for si, sc in enumerate(scenarios):
        for pi, prof in enumerate(profiles):
            traj = dynamic_trajectory_for(sc, prof)
            cache[(si, pi)] = (traj.curves, prof.block_steps, prof.scored)

    out = {"period_s": period_s,
           "blocks_per_phase": int(blocks_per_phase),
           "steps": {p.name: int(p.n_steps) for p in profiles},
           "min_block_steps": int(min(int(p.block_steps.min())
                                      for p in profiles)),
           "methods": {}}

    for name, fn in METHODS:
        per_slope = {}
        for pi, prof in enumerate(profiles):
            effs = []
            for si, sc in enumerate(scenarios):
                curves, block_steps, scored = cache[(si, pi)]
                traj = DynamicTrajectory(curves=curves, block_steps=block_steps,
                                         scored=scored, profile_name=prof.name,
                                         module=str(sc.module),
                                         geometry=str(sc.geometry))
                fn(traj, model=model, temp_c=float(sc.temp_c))
                effs.append(traj.metrics()["dynamic_efficiency_pct"])
            per_slope[prof.slope_w_m2_s] = float(np.mean(effs))
        out["methods"][name] = {
            "per_slope": per_slope,
            "aggregate_pct": aggregate_efficiency(list(per_slope.values())),
        }
    return out


def is_valid(run: dict, previous: dict | None) -> tuple[bool, str]:
    """Is this configuration a genuine test? The declared rule, D19 corrected.

    Two ways a configuration degenerates:

      BLOCKS AT THE FLOOR  any slope has a block holding fewer than
                           MIN_STEPS_PER_BLOCK control steps. Once that binds the
                           profile stops shrinking as the period grows and
                           different slopes produce identical trajectories.

      NOT RESPONDING       the step counts equal the previous period's, which is
                           the same condition observed from outside.
    """
    if run["min_block_steps"] < MIN_STEPS_PER_BLOCK:
        return False, (f"a block holds {run['min_block_steps']} step(s), "
                       f"below the declared {MIN_STEPS_PER_BLOCK}")
    if previous is not None and run["steps"] == previous["steps"]:
        return False, "step counts identical to the previous period"
    return True, ""


def check_block_convergence(scenarios, sequence: str, model: TwoStageModel,
                            cycles: int, bpp: int,
                            verbose: bool = True) -> bool:
    """Is this SEQUENCE's declared block count fine enough?

    dynamic.py declares: a block count is adequate if halving the block duration
    -- doubling the count -- moves efficiency by less than BLOCK_CONVERGENCE_PT.

    Run at the sequence's OWN declared count against twice it, at 100 ms where
    every configuration is well-formed.

    Measured to date: Sequence 30-100 converged at 6 (0.001 pt vs 12, 0.002 pt
    between 12 and 24). Sequence 10-50 FAILED at 6 (0.330 pt vs 12), because its
    low-irradiance end is steeply nonlinear. Convergence is therefore
    sequence-dependent and a count must never be inherited across sequences.
    """
    effs = {}
    for n in (bpp, 2 * bpp):
        r = run_at_period(scenarios, sequence, 0.1, model, cycles,
                          blocks_per_phase=n)
        effs[n] = r["methods"]["hybrid"]["aggregate_pct"]

    delta = abs(effs[2 * bpp] - effs[bpp])
    ok = delta < BLOCK_CONVERGENCE_PT
    if verbose:
        print(f"   sequence {sequence}, declared {bpp} blocks/phase")
        print(f"   {bpp:>4} blocks/phase (in use): {effs[bpp]:.3f}%")
        print(f"   {2*bpp:>4} blocks/phase (double): {effs[2*bpp]:.3f}%")
        print(f"   difference {delta:.3f} pt against the declared "
              f"{BLOCK_CONVERGENCE_PT} pt")
        print(f"   -> {'PASS' if ok else 'FAIL'}")
        if not ok:
            print(f"\n      The block count is too coarse FOR THIS SEQUENCE.")
            print(f"      Raise BLOCKS_PER_PHASE['{sequence}'] and re-run.")
            print("      Two things to weigh when choosing the new value:")
            print("        - raising it makes degeneracy arrive EARLIER, since")
            print("          steps are divided among blocks, so the valid period")
            print("          range shrinks")
            print("        - lower-irradiance sequences need finer blocks,")
            print("          because the curve shape changes more per unit of")
            print("          irradiance down there")
            print("      Declare the new value BEFORE re-reading the result.")
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=10)
    ap.add_argument("--sequence", default="30-100",
                    choices=list(SEQUENCES.keys()))
    ap.add_argument("--cycles", type=int, default=1)
    args = ap.parse_args()

    bpp = BLOCKS_PER_PHASE[args.sequence]

    print("P2.8b  control-period sweep: where does the funded target break?")
    print("       (revision 5 -- block count per sequence)")
    try:
        print("  " + config.provenance())
    except Exception:
        pass
    print("=" * 78)
    print("P2.8 met the target at 99.911% and found the profile does not")
    print("discriminate: across a tenfold slope range the hybrid moved 0.005 pt")
    print("and P&O moved 0.088 pt in the WRONG direction. At 100 ms no slope in")
    print("Sequence 30-100 is difficult.")
    print("\n100 ms was DECLARED, not measured. This run sweeps it to find where")
    print("the problem becomes hard.\n")
    print("acceptance, declared before this run:")
    print(f"   (0) DOUBLING the block count must move efficiency by less than")
    print(f"       {BLOCK_CONVERGENCE_PT} pt, AT THIS SEQUENCE'S OWN DECLARED "
          f"COUNT")
    print(f"   (1) the BREAK POINT is the largest period at which the hybrid")
    print(f"       still aggregates >= {TARGET_PCT:.0f}% on shaded scenarios")
    print("   (2) efficiency must be MONOTONE in the period")
    print("   (3) FAST slopes must break BEFORE slow ones")
    print(f"\nVALIDITY RULE (D19): a configuration decides a criterion only if")
    print(f"every block holds at least {MIN_STEPS_PER_BLOCK} control steps AND")
    print("its step counts differ from the previous period. Excluded rows are")
    print("still run and still printed.")
    print(f"\nBLOCK COUNT IS PER SEQUENCE. Convergence is sequence-dependent:")
    print("30-100 converged at 6 (0.001 pt); 10-50 FAILED at 6 (0.330 pt),")
    print("because its low-irradiance end is steeply nonlinear. A count")
    print("validated on one sequence must never be carried to another.")
    print(f"This run uses {bpp} blocks/phase for sequence {args.sequence}.")
    print("\nPSO and the re-seeding hybrid are EXCLUDED throughout (defect D18).\n")

    try:
        model = TwoStageModel.load(tag="c3_two_stage_full")
    except FileNotFoundError:
        print("model 'c3_two_stage_full' not found.")
        return 1

    pool = scenario_set(200)
    shaded = [s for s in pool if s.geometry != "uniform"][:args.n]
    print(f"{len(shaded)} shaded scenarios, sequence {args.sequence}, "
          f"{args.cycles} cycle(s) per slope")
    print("NOTE: P&O's outcome is bimodal -- it finds the global peak or it does")
    print("not -- so its mean is essentially the proportion that succeeded, and")
    print("it is highly sensitive to the scenario draw. Quote no P&O figure")
    print("without its scenario count.\n")

    print("0. BLOCK CONVERGENCE  (at this sequence's declared count)")
    if not check_block_convergence(shaded, args.sequence, model, args.cycles,
                                   bpp):
        return 1
    print()

    runs = []
    for period in PERIOD_SWEEP:
        print(f"   running at {1000*period:.0f} ms ...")
        runs.append(run_at_period(shaded, args.sequence, period, model,
                                  args.cycles, bpp))

    # -- validity, applied before anything is read --------------------------
    valid, excluded = [], []
    prev = None
    for r in runs:
        ok, why = is_valid(r, prev)
        (valid if ok else excluded).append((r, why))
        prev = r
    excl_periods = {r["period_s"] for r, _ in excluded}

    # -- aggregate table -----------------------------------------------------
    print("\nAGGREGATE DYNAMIC EFFICIENCY vs CONTROL PERIOD")
    names = [n for n, _ in METHODS]
    print("   " + f"{'period':>9}" + "".join(f"{n[:13]:>15}" for n in names)
          + f"{'valid':>8}")
    print("   " + "-" * (9 + 15 * len(names) + 8))
    for r in runs:
        row = "   " + f"{1000*r['period_s']:>7.0f}ms"
        for n in names:
            row += f"{r['methods'][n]['aggregate_pct']:>15.3f}"
        row += f"{'no' if r['period_s'] in excl_periods else 'yes':>8}"
        print(row)

    # -- per-slope for the hybrid -------------------------------------------
    print("\nHYBRID, PER SLOPE  (which slope fails first?)")
    slopes = sorted(runs[0]["methods"]["hybrid"]["per_slope"].keys())
    print("   " + f"{'period':>9}" + "".join(f"{s:>9.1f}" for s in slopes)
          + f"{'min blk':>10}{'valid':>8}")
    print("   " + "-" * (9 + 9 * len(slopes) + 18))
    for r in runs:
        row = "   " + f"{1000*r['period_s']:>7.0f}ms"
        for s in slopes:
            row += f"{r['methods']['hybrid']['per_slope'][s]:>9.3f}"
        row += f"{r['min_block_steps']:>10}"
        row += f"{'no' if r['period_s'] in excl_periods else 'yes':>8}"
        print(row)

    # -- the criteria --------------------------------------------------------
    print("\n" + "=" * 78)
    print("\nVERDICT")

    print("\n   VALIDITY  (declared rule, applied automatically)")
    for r, why in excluded:
        print(f"      EXCLUDED  {1000*r['period_s']:>6.0f} ms -- {why}")
    if not excluded:
        print("      every configuration is valid")
    print(f"      {len(valid)}/{len(runs)} configurations decide the criteria; "
          f"all are reported above")

    if len(valid) < 3:
        print("\n   Fewer than three valid configurations. The sweep cannot")
        print("   support a break point or a slope-ordering claim.")
        print("\n   LOWERING this sequence's block count widens the valid range,")
        print("   since steps are divided among blocks -- but check 0 must pass")
        print("   at any new value, and a lower count may fail it. Those two")
        print("   requirements pull against each other, and where they cannot")
        print("   both be met, the sequence cannot answer this question.")
        return 1

    vruns = [r for r, _ in valid]
    vaggs = [r["methods"]["hybrid"]["aggregate_pct"] for r in vruns]

    # (2) monotonicity
    non_mono = [(vruns[i]["period_s"], vaggs[i], vaggs[i - 1])
                for i in range(1, len(vaggs)) if vaggs[i] > vaggs[i - 1] + 1e-6]
    c2 = not non_mono
    print(f"\n   (2) monotone in the control period -> "
          f"{'PASS' if c2 else 'FAIL'}")
    for p, hi, lo in non_mono:
        print(f"       {1000*p:.0f} ms scored {hi:.3f}% against {lo:.3f}% at "
              f"the faster period")
    if non_mono:
        print("       Efficiency improved as the controller slowed. Something")
        print("       other than tracking difficulty is moving. Do NOT report a")
        print("       break point from this sweep.")

    # (1) the break point
    passing = [r for r, a in zip(vruns, vaggs) if a >= TARGET_PCT]
    failing = [r for r, a in zip(vruns, vaggs) if a < TARGET_PCT]
    print("\n   (1) BREAK POINT")
    if passing and failing:
        brk = max(passing, key=lambda r: r["period_s"])
        first = min(failing, key=lambda r: r["period_s"])
        print(f"       the hybrid holds >= {TARGET_PCT:.0f}% up to "
              f"{1000*brk['period_s']:.0f} ms ({1/brk['period_s']:.2f} Hz)")
        print(f"       first failure at {1000*first['period_s']:.0f} ms "
              f"({first['methods']['hybrid']['aggregate_pct']:.3f}%)")
        print("\n       HOW TO STATE THIS. A module-level optimizer runs at")
        print("       10-100 Hz. If the break point is far slower than that, the")
        print("       correct message is NOT 'the converter must be faster than")
        print("       X'. It is: THE DYNAMIC REQUIREMENT IS NOT BINDING ON ANY")
        print("       REALISTIC CONVERTER -- which removes a risk rather than")
        print("       imposing a constraint, and is the more useful thing to")
        print("       tell the partner.")
    elif passing:
        print(f"       the target was not broken within the valid range "
              f"(up to {1000*max(r['period_s'] for r in passing):.0f} ms).")
        print("       Either the valid range does not extend far enough, or the")
        print("       tracker genuinely holds the target at every rate this")
        print("       sequence can represent. The per-slope table above")
        print("       distinguishes the two: if efficiency is still near 99.9%")
        print("       at the slowest valid period, it is the latter.")
    else:
        print("       the hybrid fails at every VALID period, including the")
        print("       fastest. That contradicts P2.8's 99.911% at 100 ms.")
        print("       Investigate before reporting anything from this sweep.")

    # (3) does fast break first?
    fast, slow = max(slopes), min(slopes)
    print("\n   (3) DOES THE FAST SLOPE FAIL FIRST?  (valid configurations)")
    print(f"       {'period':>9} {'slow ' + str(slow):>12} "
          f"{'fast ' + str(fast):>12} {'gap':>10} {'min blk':>9}")
    gaps = []
    for r in vruns:
        ps = r["methods"]["hybrid"]["per_slope"]
        gap = ps[slow] - ps[fast]
        gaps.append(gap)
        print(f"       {1000*r['period_s']:>7.0f}ms {ps[slow]:>12.3f} "
              f"{ps[fast]:>12.3f} {gap:>+10.3f} {r['min_block_steps']:>9}")
    c3 = gaps[-1] > gaps[0] + 0.1
    print(f"       -> {'PASS' if c3 else 'FAIL'}  "
          f"(the slow-minus-fast gap must WIDEN as the period grows)")
    if c3:
        print("\n       Fast ramps fail earlier, as physics requires. THE")
        print("       PROFILE IS SOUND: it discriminates between slopes once the")
        print("       control rate is slow enough to make them difficult.")
        print("       P2.8's flat slope response at 100 ms was therefore a")
        print("       property of the RATE, not a defect in the instrument.")
        print("\n       Consequence: shading-pattern transitions are a CHOICE")
        print("       about strengthening the dynamic claim, not a repair for a")
        print("       broken instrument.")
    else:
        print("\n       Over valid configurations the fast slope does not fail")
        print("       earlier. Combined with P2.8's flat slope response, the")
        print("       peak movement is too small for ramp SPEED to matter at any")
        print("       rate, and only pattern transitions will separate the")
        print("       methods.")

    payload = {"sequence": args.sequence, "cycles": args.cycles,
               "n_scenarios": len(shaded),
               "period_sweep": list(PERIOD_SWEEP),
               "blocks_per_phase": bpp,
               "blocks_per_phase_all": BLOCKS_PER_PHASE,
               "min_steps_per_block_rule": MIN_STEPS_PER_BLOCK,
               "excluded_periods": sorted(excl_periods),
               "runs": runs,
               "monotone": bool(c2),
               "fast_fails_first": bool(c3)}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"control_period_sweep_{args.sequence}.json").write_text(
        json.dumps(payload, indent=2, default=float), encoding="utf-8")
    print(f"\nresults -> "
          f"{OUT / f'control_period_sweep_{args.sequence}.json'}")
    print("\nAll figures simulated, on training modules. The control period is")
    print("DECLARED throughout -- the partner's value is outstanding, and this")
    print("sweep is what tells them which values are acceptable.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())