"""
Shared plotting style and helpers (headless).

All figures generated by the phase scripts go through here so they share one
clean, publication-oriented style and land in results/figures/. Figures are
regenerable from seeded data, so they are git-ignored; the code that makes them
is the tracked artefact.
"""
from __future__ import annotations
import matplotlib
matplotlib.use("Agg")  # headless: no display, deterministic file output
import matplotlib.pyplot as plt

from . import config

FIG_DIR = config.RESULTS_DIR / "figures"
FIG_DIR.mkdir(exist_ok=True)

# Cove-ish categorical palette, matched to the report style
BLUE, ORANGE, TEAL, GRAY = "#2a78d6", "#eb6834", "#1baf7a", "#898781"

plt.rcParams.update({
    "figure.dpi": 120,
    "savefig.dpi": 150,
    "savefig.bbox": "tight",
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.titleweight": "normal",
    "axes.grid": True,
    "grid.color": "#e1e0d9",
    "grid.linewidth": 0.8,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.edgecolor": "#c3c2b7",
    "legend.frameon": False,
})


def save_fig(fig, name: str):
    """Save a figure to results/figures/<name>.png and return its path."""
    path = FIG_DIR / f"{name}.png"
    fig.savefig(path)
    plt.close(fig)
    return path
